/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.networkproject;

import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Kevser
 */
public class GUI1 extends javax.swing.JFrame {
private java.awt.Button secilenButon = null;
private javax.swing.JLabel[] ucgenler;


    /**
     * Creates new form GUI1
     */
    public GUI1() {
        initComponents();
        

        button_0_0.addActionListener(e -> secilenButon = button_0_0);
button_0_1.addActionListener(e -> secilenButon = button_0_1);
button2.addActionListener(e -> secilenButon = button2);
button3.addActionListener(e -> secilenButon = button3);
button4.addActionListener(e -> secilenButon = button4);
button5.addActionListener(e -> secilenButon = button5);
button6.addActionListener(e -> secilenButon = button6);
button7.addActionListener(e -> secilenButon = button7);
button8.addActionListener(e -> secilenButon = button8);
button9.addActionListener(e -> secilenButon = button9);
button10.addActionListener(e -> secilenButon = button10);
button11.addActionListener(e -> secilenButon = button11);
//jLayeredPane1.setLayer(jLabel1, 0);  // arka plan en alt
//// Butonlar üstte (taşlar)
//jLayeredPane1.setLayer(button_0_0, 1);
//jLayeredPane1.setLayer(button_0_1, 1);
//jLayeredPane1.setLayer(button2, 1);
//jLayeredPane1.setLayer(button3, 1);
//jLayeredPane1.setLayer(button4, 1);
//jLayeredPane1.setLayer(button5, 1);
//jLayeredPane1.setLayer(button6, 1);
//jLayeredPane1.setLayer(button7, 1);
//jLayeredPane1.setLayer(button8, 1);
//jLayeredPane1.setLayer(button9, 1);
//jLayeredPane1.setLayer(button10, 1);
//jLayeredPane1.setLayer(button11, 1);

jLayeredPane1.setLayer(jLabel1, 0);  // Arka plan
        for (int i = 0; i < jLayeredPane1.getComponentCount(); i++) {
            java.awt.Component c = jLayeredPane1.getComponent(i);
            if (c instanceof java.awt.Button) {
                jLayeredPane1.setLayer(c, 1);
            }
        }

// ...
ucgenler = new javax.swing.JLabel[] {
    jLabelucgen0, jLabelucgen1, jLabelucgen2, jLabelucgen3, jLabelucgen4,
    jLabelucgen5, jLabelucgen6, jLabelucgen7, jLabelucgen8, jLabelucgen9,
    jLabelucgen10, jLabelucgen11
    // üsttekiler sadece 12 tanesi, senin 24 taneyse tümünü yaz
};

// Örnek olarak jLabelucgen2 için:
for (JLabel ucgen : ucgenler) {
    ucgen.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            if (secilenButon != null) {
                java.awt.Container eskiParent = secilenButon.getParent();
                eskiParent.remove(secilenButon);

                ucgen.add(secilenButon);
                int y = 3 + (ucgen.getComponentCount() - 1) * 30;
                secilenButon.setLocation(0, y);

                ucgen.revalidate();
                ucgen.repaint();
                secilenButon = null;
            }
        }
    });
}


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        ZarAtbutton = new java.awt.Button();
        jLabelzar1 = new javax.swing.JLabel();
        jLabelzar2 = new javax.swing.JLabel();
        jLabelucgen0 = new javax.swing.JLabel();
        button_0_1 = new java.awt.Button();
        button_0_0 = new java.awt.Button();
        jLabelucgen5 = new javax.swing.JLabel();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        button4 = new java.awt.Button();
        button5 = new java.awt.Button();
        button6 = new java.awt.Button();
        jLabelucgen7 = new javax.swing.JLabel();
        button7 = new java.awt.Button();
        button8 = new java.awt.Button();
        button9 = new java.awt.Button();
        jLabelucgen11 = new javax.swing.JLabel();
        button10 = new java.awt.Button();
        button11 = new java.awt.Button();
        jLabelucgen1 = new javax.swing.JLabel();
        jLabelucgen2 = new javax.swing.JLabel();
        jLabelucgen3 = new javax.swing.JLabel();
        jLabelucgen4 = new javax.swing.JLabel();
        jLabelucgen6 = new javax.swing.JLabel();
        jLabelucgen8 = new javax.swing.JLabel();
        jLabelucgen9 = new javax.swing.JLabel();
        jLabelucgen10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/networkproject/images/backgomman.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 500));

        ZarAtbutton.setLabel("zatAt");
        ZarAtbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZarAtbuttonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(ZarAtbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 50, -1));
        jLayeredPane1.add(jLabelzar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 30, 30));

        jLabelzar2.setText("jLabel3");
        jLayeredPane1.add(jLabelzar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 30, 30));

        jLabelucgen0.setText("jLabel2");
        jLayeredPane1.add(jLabelucgen0, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 30, 150));
        jLayeredPane1.add(button_0_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 30, 30));
        jLayeredPane1.add(button_0_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 30, 30));

        jLabelucgen5.setText("jLabel3");
        jLayeredPane1.add(jLabelucgen5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 30, 150));

        button2.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 30, 30));

        button3.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane1.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 30, 30));

        button4.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane1.add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 30, 30));

        button5.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane1.add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 30, 30));

        button6.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane1.add(button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 30, 30));

        jLabelucgen7.setText("jLabel4");
        jLayeredPane1.add(jLabelucgen7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 30, 150));

        button7.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane1.add(button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 30, 30));

        button8.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane1.add(button8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 30, 30));

        button9.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane1.add(button9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 30, 30));

        jLabelucgen11.setText("jLabel5");
        jLayeredPane1.add(jLabelucgen11, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 30, 30, 150));
        jLayeredPane1.add(button10, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 30, 30, 30));
        jLayeredPane1.add(button11, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 60, 30, 30));

        jLabelucgen1.setText("jLabel6");
        jLayeredPane1.add(jLabelucgen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 30, 150));

        jLabelucgen2.setText("jLabel7");
        jLayeredPane1.add(jLabelucgen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 30, 30, 150));

        jLabelucgen3.setText("jLabel8");
        jLayeredPane1.add(jLabelucgen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 30, 150));

        jLabelucgen4.setText("jLabel9");
        jLayeredPane1.add(jLabelucgen4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 30, 150));

        jLabelucgen6.setText("jLabel10");
        jLayeredPane1.add(jLabelucgen6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 30, 150));

        jLabelucgen8.setText("jLabel11");
        jLayeredPane1.add(jLabelucgen8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 30, 150));

        jLabelucgen9.setText("jLabel12");
        jLayeredPane1.add(jLabelucgen9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 30, 150));

        jLabelucgen10.setText("jLabel13");
        jLayeredPane1.add(jLabelucgen10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 30, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ZarAtbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZarAtbuttonActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_ZarAtbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button ZarAtbutton;
    private java.awt.Button button10;
    private java.awt.Button button11;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private java.awt.Button button5;
    private java.awt.Button button6;
    private java.awt.Button button7;
    private java.awt.Button button8;
    private java.awt.Button button9;
    private java.awt.Button button_0_0;
    private java.awt.Button button_0_1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelucgen0;
    private javax.swing.JLabel jLabelucgen1;
    private javax.swing.JLabel jLabelucgen10;
    private javax.swing.JLabel jLabelucgen11;
    private javax.swing.JLabel jLabelucgen2;
    private javax.swing.JLabel jLabelucgen3;
    private javax.swing.JLabel jLabelucgen4;
    private javax.swing.JLabel jLabelucgen5;
    private javax.swing.JLabel jLabelucgen6;
    private javax.swing.JLabel jLabelucgen7;
    private javax.swing.JLabel jLabelucgen8;
    private javax.swing.JLabel jLabelucgen9;
    private javax.swing.JLabel jLabelzar1;
    private javax.swing.JLabel jLabelzar2;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
